"""
SSTG — Exam Layout Templates
==============================
Backend for the "complete editor for schedules" — lets an admin define
multiple exam-timetable export layouts (field placement, grouping,
orientation, footer text, warning banners) instead of a single hardcoded
PDF/Excel format. An ExamSession can pick a specific template; otherwise
the org-wide default template is used.
"""
from __future__ import annotations
from typing import List
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from database import get_db
from security import get_current_user, require_admin
from models import User, ExamLayoutTemplate, ExamSession
from schemas import ExamLayoutTemplateCreate, ExamLayoutTemplateUpdate, ExamLayoutTemplateOut

router = APIRouter(tags=["Exam Layout Templates"])


def _ensure_one_default(db: Session, exclude_id: str | None = None):
    """Guarantee exactly one default template exists once at least one exists."""
    has_default = db.query(ExamLayoutTemplate).filter(
        ExamLayoutTemplate.is_default == True,  # noqa: E712
    ).first()
    if has_default:
        return
    first = db.query(ExamLayoutTemplate).filter(
        ExamLayoutTemplate.id != exclude_id if exclude_id else True
    ).first()
    if first:
        first.is_default = True
        db.commit()


def _seed_default_if_empty(db: Session):
    """First-run convenience: ship one sensible default template so exports
    work immediately without forcing the admin through the editor first."""
    if db.query(ExamLayoutTemplate).count() > 0:
        return
    db.add(ExamLayoutTemplate(
        name="Standard (Full Detail)",
        is_default=True,
        group_by="day",
        orientation="landscape",
        show_duration=True,
        show_invigilator=True,
        show_room=True,
        show_notes=False,
        show_practical_tag=True,
        footer_text="Generated by Smart Admin — schedule subject to change until published.",
        warning_text=None,
    ))
    db.commit()


@router.get("/exam-layouts", response_model=List[ExamLayoutTemplateOut])
def list_layouts(db: Session = Depends(get_db), _: User = Depends(get_current_user)):
    _seed_default_if_empty(db)
    return db.query(ExamLayoutTemplate).order_by(
        ExamLayoutTemplate.is_default.desc(), ExamLayoutTemplate.name
    ).all()


@router.get("/exam-layouts/default", response_model=ExamLayoutTemplateOut)
def get_default_layout(db: Session = Depends(get_db), _: User = Depends(get_current_user)):
    _seed_default_if_empty(db)
    default = db.query(ExamLayoutTemplate).filter(
        ExamLayoutTemplate.is_default == True  # noqa: E712
    ).first()
    if not default:
        raise HTTPException(404, "No exam layout templates configured")
    return default


@router.get("/exam-layouts/{layout_id}", response_model=ExamLayoutTemplateOut)
def get_layout(layout_id: str, db: Session = Depends(get_db), _: User = Depends(get_current_user)):
    layout = db.get(ExamLayoutTemplate, layout_id)
    if not layout:
        raise HTTPException(404, "Layout template not found")
    return layout


@router.post("/exam-layouts", response_model=ExamLayoutTemplateOut, status_code=201)
def create_layout(
    data: ExamLayoutTemplateCreate,
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    if data.group_by not in ("day", "class"):
        raise HTTPException(400, "group_by must be 'day' or 'class'")
    if data.orientation not in ("landscape", "portrait"):
        raise HTTPException(400, "orientation must be 'landscape' or 'portrait'")

    layout = ExamLayoutTemplate(**data.model_dump())
    db.add(layout)
    db.flush()

    if layout.is_default:
        # Only one default at a time — clear the flag on every other template.
        db.query(ExamLayoutTemplate).filter(
            ExamLayoutTemplate.id != layout.id
        ).update({"is_default": False})

    db.commit()
    db.refresh(layout)
    _ensure_one_default(db)
    return layout


@router.put("/exam-layouts/{layout_id}", response_model=ExamLayoutTemplateOut)
def update_layout(
    layout_id: str,
    data: ExamLayoutTemplateUpdate,
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    layout = db.get(ExamLayoutTemplate, layout_id)
    if not layout:
        raise HTTPException(404, "Layout template not found")
    for field, val in data.model_dump(exclude_none=True).items():
        setattr(layout, field, val)
    db.commit()
    db.refresh(layout)
    return layout


@router.put("/exam-layouts/{layout_id}/set-default", response_model=ExamLayoutTemplateOut)
def set_default_layout(
    layout_id: str,
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    layout = db.get(ExamLayoutTemplate, layout_id)
    if not layout:
        raise HTTPException(404, "Layout template not found")
    db.query(ExamLayoutTemplate).update({"is_default": False})
    layout.is_default = True
    db.commit()
    db.refresh(layout)
    return layout


@router.delete("/exam-layouts/{layout_id}")
def delete_layout(
    layout_id: str,
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    layout = db.get(ExamLayoutTemplate, layout_id)
    if not layout:
        raise HTTPException(404, "Layout template not found")
    if db.query(ExamLayoutTemplate).count() <= 1:
        raise HTTPException(400, "Cannot delete the last remaining layout template")

    was_default = layout.is_default
    # Any exam sessions pinned to this template fall back to the default —
    # never leave a session referencing a deleted template.
    db.query(ExamSession).filter(ExamSession.layout_template_id == layout_id).update(
        {"layout_template_id": None}
    )
    db.delete(layout)
    db.commit()
    if was_default:
        _ensure_one_default(db)
    return {"status": "deleted"}


@router.put("/exams/sessions/{session_id}/layout")
def set_session_layout(
    session_id: str,
    layout_id: str | None = None,
    db: Session = Depends(get_db),
    _: User = Depends(get_current_user),
):
    """Pin a specific layout template to one exam session (None = use the default)."""
    session = db.get(ExamSession, session_id)
    if not session:
        raise HTTPException(404, "Exam session not found")
    if layout_id:
        layout = db.get(ExamLayoutTemplate, layout_id)
        if not layout:
            raise HTTPException(404, "Layout template not found")
    session.layout_template_id = layout_id
    db.commit()
    return {"status": "saved", "layout_template_id": layout_id}
