"""
SSTG — Timetable Layout Templates
====================================
Twin of exam_layouts.py for regular class timetables — completes the
"editor for schedules" (plural: both exams and timetables) requested
alongside curriculum-aware onboarding. Controls orientation, footer text,
and warning banners on timetable PDF/Excel/CSV exports. A TimetableDraft
can pin a specific template; otherwise the org-wide default is used.
"""
from __future__ import annotations
from typing import List
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from database import get_db
from security import get_current_user, require_admin
from models import User, TimetableLayoutTemplate, TimetableDraft
from schemas import (
    TimetableLayoutTemplateCreate,
    TimetableLayoutTemplateUpdate,
    TimetableLayoutTemplateOut,
)

router = APIRouter(tags=["Timetable Layout Templates"])


def _ensure_one_default(db: Session):
    has_default = db.query(TimetableLayoutTemplate).filter(
        TimetableLayoutTemplate.is_default == True  # noqa: E712
    ).first()
    if has_default:
        return
    first = db.query(TimetableLayoutTemplate).first()
    if first:
        first.is_default = True
        db.commit()


def _seed_default_if_empty(db: Session):
    if db.query(TimetableLayoutTemplate).count() > 0:
        return
    db.add(TimetableLayoutTemplate(
        name="Standard",
        is_default=True,
        orientation="landscape",
        show_locked_badge=True,
        show_room=False,
        footer_text="Generated by Smart Admin — schedule subject to change until activated.",
        warning_text=None,
    ))
    db.commit()


@router.get("/timetable-layouts", response_model=List[TimetableLayoutTemplateOut])
def list_layouts(db: Session = Depends(get_db), _: User = Depends(get_current_user)):
    _seed_default_if_empty(db)
    return db.query(TimetableLayoutTemplate).order_by(
        TimetableLayoutTemplate.is_default.desc(), TimetableLayoutTemplate.name
    ).all()


@router.get("/timetable-layouts/default", response_model=TimetableLayoutTemplateOut)
def get_default_layout(db: Session = Depends(get_db), _: User = Depends(get_current_user)):
    _seed_default_if_empty(db)
    default = db.query(TimetableLayoutTemplate).filter(
        TimetableLayoutTemplate.is_default == True  # noqa: E712
    ).first()
    if not default:
        raise HTTPException(404, "No timetable layout templates configured")
    return default


@router.post("/timetable-layouts", response_model=TimetableLayoutTemplateOut, status_code=201)
def create_layout(
    data: TimetableLayoutTemplateCreate,
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    if data.orientation not in ("landscape", "portrait"):
        raise HTTPException(400, "orientation must be 'landscape' or 'portrait'")

    layout = TimetableLayoutTemplate(**data.model_dump())
    db.add(layout)
    db.flush()

    if layout.is_default:
        db.query(TimetableLayoutTemplate).filter(
            TimetableLayoutTemplate.id != layout.id
        ).update({"is_default": False})

    db.commit()
    db.refresh(layout)
    _ensure_one_default(db)
    return layout


@router.put("/timetable-layouts/{layout_id}", response_model=TimetableLayoutTemplateOut)
def update_layout(
    layout_id: str,
    data: TimetableLayoutTemplateUpdate,
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    layout = db.get(TimetableLayoutTemplate, layout_id)
    if not layout:
        raise HTTPException(404, "Layout template not found")
    for field, val in data.model_dump(exclude_none=True).items():
        setattr(layout, field, val)
    db.commit()
    db.refresh(layout)
    return layout


@router.put("/timetable-layouts/{layout_id}/set-default", response_model=TimetableLayoutTemplateOut)
def set_default_layout(
    layout_id: str,
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    layout = db.get(TimetableLayoutTemplate, layout_id)
    if not layout:
        raise HTTPException(404, "Layout template not found")
    db.query(TimetableLayoutTemplate).update({"is_default": False})
    layout.is_default = True
    db.commit()
    db.refresh(layout)
    return layout


@router.delete("/timetable-layouts/{layout_id}")
def delete_layout(
    layout_id: str,
    db: Session = Depends(get_db),
    _: User = Depends(require_admin),
):
    layout = db.get(TimetableLayoutTemplate, layout_id)
    if not layout:
        raise HTTPException(404, "Layout template not found")
    if db.query(TimetableLayoutTemplate).count() <= 1:
        raise HTTPException(400, "Cannot delete the last remaining layout template")

    was_default = layout.is_default
    db.query(TimetableDraft).filter(TimetableDraft.layout_template_id == layout_id).update(
        {"layout_template_id": None}
    )
    db.delete(layout)
    db.commit()
    if was_default:
        _ensure_one_default(db)
    return {"status": "deleted"}


@router.put("/schedule/drafts/{draft_id}/layout")
def set_draft_layout(
    draft_id: str,
    layout_id: str | None = None,
    db: Session = Depends(get_db),
    _: User = Depends(get_current_user),
):
    """Pin a specific layout template to one timetable draft (None = use the default)."""
    draft = db.get(TimetableDraft, draft_id)
    if not draft:
        raise HTTPException(404, "Draft not found")
    if layout_id:
        layout = db.get(TimetableLayoutTemplate, layout_id)
        if not layout:
            raise HTTPException(404, "Layout template not found")
    draft.layout_template_id = layout_id
    db.commit()
    return {"status": "saved", "layout_template_id": layout_id}
